// <auto-generated />
namespace DeversWeWatch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ladetillbegränsningar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ladetillbegränsningar));
        
        string IMigrationMetadata.Id
        {
            get { return "201604250816566_Lade till begränsningar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
